### ISSUE TITLE
確認餘額計算的方式

### ISSUE THREAD

**Issue by linroex** [lekoOwO/CC-Food#2]
我試圖計算每個人餘額，但發現算不出來（跟舊系統比）

```sql
SELECT
	users.display_name,
	t.*
FROM (
	SELECT
		user_id,
		sum(total) AS total
	FROM
		purchases
	LEFT JOIN purchase_details ON purchases.id = purchase_details.purchase_id
WHERE
	purchases.deleted_at IS NULL
GROUP BY
	user_id) AS t
	LEFT JOIN users ON t.user_id = users.id
ORDER BY
	total DESC
```

purchases.deleted_at  這個欄位好像沒用到？

**Comment by lekoOwO** [comment]
我可以新增一個管理頁面處理這個問題

**Comment by lekoOwO** [comment]
未結帳的訂單的計算方式在 https://github.com/lekoOwO/CC-Food/blob/f8efd86dec93a79e7068f63dd4da9084a6883033/api.go#L280

基本上是找所有 `payment_id` IS `NULL` 的 `purchase`
`deleted_at` 欄位是閒置的沒錯

**Comment by lekoOwO** [comment]
https://github.com/lekoOwO/CC-Food-Client/commit/2912998dfa9ae85391b5f4944cc28347516315bb
新增了欠錢大戶頁面
