### ISSUE TITLE
購物流程的調整

### ISSUE THREAD

**Issue by linroex** [lekoOwO/CC-Food#4]
- 購物失敗（call api）時沒有錯誤訊息，會誤以為有購物成功
- 會搞不清楚「新增一個購物項目」跟「結帳」的按鈕，導致很容易建立 0 元訂單
- 結帳成功的訊息： 顯示金額等等

**Comment by lekoOwO** [comment]
購物失敗應該會顯示購買失敗才對 https://github.com/lekoOwO/CC-Food-Client/blob/5bdcf613dceafba7098228d3d30397f3f2391bfc/buy.go#L108

**Comment by lekoOwO** [comment]
https://github.com/lekoOwO/CC-Food-Client/commit/c86bd2ca501a65005bbba0296f9269092b5ed5ec
