### ISSUE TITLE
整體流程簡化

### ISSUE THREAD

**Issue by linroex** [lekoOwO/CC-Food#5]
現在要「購買商品」所需要按的步驟（要按的按鍵數量）變很多，不太方便

**Comment by linroex** [comment]
另外，會有人是想要直接打金額（心算多筆商品），但以現在流程來說會很麻煩

**Comment by lekoOwO** [comment]
下個版本進入系統後直接跳進購物頁面好了
直接打金額就用`其他`商品 (?

**Comment by lekoOwO** [comment]
https://github.com/lekoOwO/CC-Food-Client/commit/c86bd2ca501a65005bbba0296f9269092b5ed5ec
