### ISSUE TITLE
匯入資料確認

### ISSUE THREAD

**Issue by linroex** [lekoOwO/CC-Food#6]
有些人有「新增購物 負 100 元」來取代結帳的狀況，不確定這種資料在匯入新系統時如何處理

**Comment by lekoOwO** [comment]
會以購買 `-100` 個 `其他` 商品的方式處理
https://github.com/lekoOwO/CC-Food/commit/3874490ded2dc0ecfe985bd9f1b1973d5195d005 即是為了這個情況調整的
